### ISSUE TITLE
implement yubikey SetKey similar to SetCertificate?

### ISSUE THREAD

**Issue by colemickens** [go-piv/piv-go#77]
If I managed to get the APDU commands working for yubikeys to import their private key, would you accept a PR for that functionality?

**Comment by ericchiang** [comment]
Been a while Cole 😀 hope you're doing well!

The reason I've omitted this feature is because I think it's a bit of an anti-pattern. You should be able to attest a key is in hardware, or there's not a huge benefit in having hardware backed keys.

So, I don't understand the use case of importing a key. If you've gotten some ideas happy to hear them, but otherwise I'd like to avoid implementing loading private keys.

**Comment by ericchiang** [comment]
Closed by #83
